THDShop/THDShop/Areas/Manager/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;

namespace THDShop.Areas.Manager.Controllers
{
    public class BillController : Controller
    {
        QLLaptopShopEntities database = new QLLaptopShopEntities();

        // GET: Manager/BILL
        public ActionResult Index()
        {
            if (Session["IDQL"] != null || Session["IDNV"] != null)
            {
                return View(database.BILLs.ToList());
            }
            return Redirect("/LoginCustomer/LoginAccount");
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var hoadon = database.BILLs.Find(id);
            if (hoadon == null)
            {
                return HttpNotFound();
            }
            return View(hoadon);
        }
        public ActionResult Searchid(int id)
        {
            var list = database.BILLs.Where(p => p.ID==id).ToList();
            return View(list);
        }
    }
}

THDShop/THDShop/Areas/Manager/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using THDShop;
using THDShop.ViewModel;
using THDShop.ViewModel.Product;


namespace THDShop.Areas.Manager.Controllers
{
    public class ProductController : Controller 
    {
        // GET: Manager/Product
        private QLLaptopShopEntities _context = new QLLaptopShopEntities();
        
      
        
        public ProductController( )
        {
            ProductSingleton.Instance.Init(_context);
        }

     
        public ActionResult Index(int id = 0)
        {
            //var query = from c in _context.PRODUCTS
            //            select new ProductDTO
            //            {
            //                ID = c.ID,
            //                NAME = c.NAME,
            //                PRICE = c.PRICE, 
            //                ORI_PRICE = c.ORI_PRICE,
            //                DESCRIPTION = c.DESCRIPTION,
            //                CATEGORYNAME = c.CATEGORy.NAME,
            //                IDCATEGORY = c.IDCATEGORY,
            //                QUANTITY = c.QUANTITY,
            //                IMAGE = c.IMAGE,
            //                DESCRIPTION_CPU = c.DESCRIPTION_CPU,
            //                DESCRIPTION_RAM = c.DESCRIPTION_RAM,
            //                DESCRIPTION_STORAGE = c.DESCRIPTION_STORAGE,
            //                DESCRIPTION_CARD = c.DESCRIPTION_CARD,
            //                DESCRIPTION_SCREEN = c.DESCRIPTION_SCREEN,
            //                DESCRIPTION_WEIGHT = c.DESCRIPTION_WEIGHT,
            //            };
            //return View(query.ToList());
            //var query = ProductSingleton.Instance.listProduct;
            //return View(query.ToList());
            if (Session["IDQL"] != null)
            {
                var links = from l in _context.PRODUCTS
                            select l;
                if (id != 0)
                {
                    links = links.Where(x => x.ID == id);
                    return View(links);
                }
                return View(links);
            }
            return Redirect("/LoginCustomer/LoginAccount");
        }
        
        public ActionResult Create()
        {
            var categorylist = _context.CATEGORIES.ToList().Select(
            x => new SelectListItem
            {
                Text = x.NAME,
                Value = Convert.ToString(x.ID)
            }
           );
            ViewBag.Categories = categorylist;
            CreateProductInput prod = new CreateProductInput();
            return View(prod);

        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(CreateProductInput model)
        {

            CalculateClient sales = new CalculateClient(new Sale_Price());
            var entity = new PRODUCT();
            if (model != null)
            {
                entity = new PRODUCT();
                var categorylist = _context.CATEGORIES.ToList().Select(
                x => new SelectListItem
                {
                    Text = x.NAME,
                    Value = Convert.ToString(x.ID)
                }
                );
                ViewBag.Categories = categorylist;
                if (model.UploadImage != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(model.UploadImage.FileName);
                    string extent = Path.GetExtension(model.UploadImage.FileName);
                    filename = filename + extent;
                    model.IMAGE = "~/Assets/Images/" + filename;
                    model.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Assets/Images"), filename));
                }
                entity.IMAGE = model.IMAGE;


                    if (ModelState.IsValid)
                {
                    var i = model.ORI_PRICE;
                    entity.ID = model.ID;
                    entity.NAME = model.NAME;
                    entity.ORI_PRICE = model.ORI_PRICE.HasValue ? model.ORI_PRICE.Value : 0;
                    entity.PRICE = sales.Calculate((int)i);
                    entity.QUANTITY = model.QUANTITY.HasValue ? model.QUANTITY.Value : 0;
                    entity.USD_PRICE = model.USD_PRICE(1);
                    entity.DESCRIPTION = model.DESCRIPTION;
                    entity.DESCRIPTION_CPU = model.DESCRIPTION_CPU;
                    entity.DESCRIPTION_RAM = model.DESCRIPTION_RAM;
                    entity.DESCRIPTION_STORAGE = model.DESCRIPTION_STORAGE;
                    entity.DESCRIPTION_CARD = model.DESCRIPTION_CARD;
                    entity.DESCRIPTION_SCREEN = model.DESCRIPTION_SCREEN;
                    entity.DESCRIPTION_WEIGHT = model.DESCRIPTION_WEIGHT;
                    entity.IDCATEGORY = model.IDCATEGORY;
                    _context.PRODUCTS.Add(entity);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {

                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }
        public ActionResult Edit(int ID)
        {
            var entity = _context.PRODUCTS.Find(ID);
            var model = new UpdateProductInput();
            var categorylist = _context.CATEGORIES.ToList().Select(
                x => new SelectListItem
                {
                    Text = x.NAME,
                    Value = Convert.ToString(x.ID)
                }
                );
            ViewBag.Categories = categorylist;
            model.ID = entity.ID;
            model.HOTPRODUCT = entity.HOTPRODUCT;
            model.NAME = entity.NAME;
            model.PRICE = entity.PRICE;
            model.ORI_PRICE = entity.ORI_PRICE;
            model.QUANTITY = entity.QUANTITY;
            model.DESCRIPTION = entity.DESCRIPTION;
            model.DESCRIPTION_CPU = entity.DESCRIPTION_CPU;
            model.DESCRIPTION_RAM = entity.DESCRIPTION_RAM;
            model.DESCRIPTION_STORAGE = entity.DESCRIPTION_STORAGE;
            model.DESCRIPTION_CARD = entity.DESCRIPTION_CARD;
            model.DESCRIPTION_SCREEN = entity.DESCRIPTION_SCREEN;
            model.DESCRIPTION_WEIGHT = entity.DESCRIPTION_WEIGHT;
            model.IDCATEGORY = entity.IDCATEGORY;
            model.IMAGE = entity.IMAGE;
            return View(model);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(UpdateProductInput model)
        {
            var entity = new PRODUCT();
            if (model == null)
                return HttpNotFound();

            var categorylist = _context.CATEGORIES.ToList().Select(
                x => new SelectListItem
                {
                    Text = x.NAME,
                    Value = Convert.ToString(x.ID)
                }
                );
            ViewBag.Categories = categorylist;

            if (model.UploadImage != null)
            {
                string filename = Path.GetFileNameWithoutExtension(model.UploadImage.FileName);
                string extent = Path.GetExtension(model.UploadImage.FileName);
                filename = filename + extent;
                model.IMAGE = "~/Assets/Images/" + filename;
                model.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Assets/Images"), filename));

            }
            entity.ID = model.ID;
            entity.HOTPRODUCT = model.HOTPRODUCT;
            entity.NAME = model.NAME;
            entity.PRICE = model.PRICE.HasValue ? model.PRICE.Value : 0;
            entity.ORI_PRICE = model.ORI_PRICE.HasValue ? model.ORI_PRICE.Value : 0;
            entity.USD_PRICE = model.USD_PRICE(1);
            entity.QUANTITY = model.QUANTITY.HasValue ? model.QUANTITY.Value : 0;
            entity.DESCRIPTION = model.DESCRIPTION;
            entity.DESCRIPTION_CPU = model.DESCRIPTION_CPU;
            entity.DESCRIPTION_RAM = model.DESCRIPTION_RAM;
            entity.DESCRIPTION_STORAGE = model.DESCRIPTION_STORAGE;
            entity.DESCRIPTION_CARD = model.DESCRIPTION_CARD;
            entity.DESCRIPTION_SCREEN = model.DESCRIPTION_SCREEN;
            entity.DESCRIPTION_WEIGHT = model.DESCRIPTION_WEIGHT;
            entity.IDCATEGORY = model.IDCATEGORY;
            entity.IMAGE = model.IMAGE;

            this._context.Entry(entity).State = EntityState.Modified;
            this._context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id, PRODUCT prod)
        {
            try
            {
                prod = _context.PRODUCTS.Where(s => s.ID == id).FirstOrDefault();
                _context.PRODUCTS.Remove(prod);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Dữ liệu này đang được sử dụng bởi một bảng khác");
            }
        }


        public ActionResult Detail(DetailProductDTO model, int ID)
        {
            var query = from c in _context.PRODUCTS
                        where c.ID == ID
                        select new DetailProductDTO
                        {
                            ID = c.ID,
                           // HOTPRODUCT = c.HOTPRODUCTS,
                            NAME = c.NAME,
                            PRICE = c.PRICE,
                            ORI_PRICE = c.ORI_PRICE,
                            QUANTITY = c.QUANTITY,
                            DESCRIPTION = c.DESCRIPTION,
                            IMAGE = c.IMAGE,

THDShop/THDShop/Areas/Manager/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ClosedXML.Excel;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.IO;
using THDShop.ViewModel.Report;

namespace THDShop.Areas.Manager.Controllers
{
    public class ReportController : Controller
    {
        QLLaptopShopEntities database = new QLLaptopShopEntities();

        // GET: Manager/Report
        public ActionResult Index()
        {
            if (Session["IDQL"] != null)
            {
                return View(database.REPORTs.ToList());
            }
            return Redirect("/LoginCustomer/LoginAccount");
        }

        // GET: Manager/Report/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Manager/Report/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Manager/Report/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Manager/Report/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Manager/Report/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Manager/Report/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Manager/Report/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public FileResult Export()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[4]{
                new DataColumn("ID"),
                new DataColumn("TOTALMONEY"),
                new DataColumn("DATETIME"),
                new DataColumn("DATETIMEEXPORT")
            });
            var bill = from c in database.BILLs.ToList() select c;
            foreach (var b in bill)
            {
                dt.Rows.Add(b.ID, b.TOTALMONEY, b.DATETIME, DateTime.Now);
            }
            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ReportLaptopShop.xlsx");
                }
            }
           
    }
        public ActionResult Searchday(int day)
        { 
            int month = day;
            var list = database.REPORTs.Where(p => p.DATERP.Value.Month == month).ToList();
            return View(list);
        }
    }
}

THDShop/THDShop/Areas/Manager/Views/Bill/Details.cshtml
@model THDShop.BILL

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BILL</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TOTALMONEY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TOTALMONEY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATETIME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATETIME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NOTE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOTE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.METHODS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.METHODS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ORDER.NOTE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ORDER.NOTE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.STAFF.NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.STAFF.NAME)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

THDShop/THDShop/Areas/Manager/Views/Bill/Index.cshtml
@model IEnumerable<THDShop.BILL>

@{
    ViewBag.Title = "Index";
}
@using (Html.BeginForm("Searchid", "Bill"))
{
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Hóa Đơn</h1>
        <div class="input-group">
            <input type="text" name="id" class="form-control bg-light border-0 small" placeholder="Nhập mã hóa đơn"
                   aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="text-center">
        <div>
            <div class="tbl-header">
                <table cellpadding="0" cellspacing="0" border="0">
                    <thead class="table-header">
                        <tr>
                            <th class="header__item">
                                <a class="filter__link filter__link--number" id="id" href="#">
                                    Thời Gian
                                </a>
                            </th>
                            <th class="header__item">
                                <a class="filter__link filter__link--number" id="name" href="#">
                                    Mã HĐ
                                </a>
                            </th>
                            <th class="header__item">
                                <a class="filter__link" id="cate" href="#">
                                    Khách Hàng
                                </a>
                            </th>
                            <th class="header__item">
                                <a class="filter__link filter__link--number" id="oriprice" href="#">
                                    SĐT
                                </a>
                            </th>
                            <th class="header__item">
                                <a class="filter__link filter__link--number" id="price" href="#">
                                    Tổng Tiền
                                </a>
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div>
                <table cellpadding="0" cellspacing="0" border="0">
                    <tbody class="table-content">
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr class="table-row">
                                    <td class="table-data">
                                        @(item.DATETIME.ToString("dd/MM HH:mm"))
                                    </td>
                                    <td class="table-data">
                                        @Html.DisplayFor(modelItem => item.ID)
                                    </td>
                                    <td class="table-data">
                                        @Html.DisplayFor(modelItem => item.ORDER.DELI_ADDRESS.NAME)
                                    </td>
                                    <td class="table-data">
                                        @Html.DisplayFor(modelItem => item.ORDER.DELI_ADDRESS.PHONE)
                                    </td>
                                    <td class="table-data">
                                        @Html.DisplayFor(modelItem => item.TOTALMONEY)
                                    </td>
                                    <td style="display: flex;align-content: center;flex-wrap: wrap;flex-direction: column;">
                                        <a href="@Url.Action("Edit", "Bill", new { id = item.ID })" class="btn btn-sm btn-warning" style="margin-bottom: 5px;">Sửa</a>
                                        <a href="@Url.Action("Detail", "Bill", new { id = item.ID })" class="btn btn-sm btn-info" style="margin-bottom: 5px;">Chi Tiết</a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    }

THDShop/THDShop/Areas/Manager/Views/Bill/Report.cshtml
@model IEnumerable<THDShop.REPORT>

@{
}
<div class="text-center">
    <div>
        <div class="tbl-header">
            <table cellpadding="0" cellspacing="0" border="0">
                <thead class="table-header">
                    <tr>
                        <th class="header__item">
                            <a class="filter__link filter__link--number" id="id" href="#">
                                Ma HD
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link filter__link--number" id="name" href="#">
                                @Html.DisplayNameFor(model => model.DATE)
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link" id="cate" href="#">
                                @Html.DisplayNameFor(model => model.BILL.ORI_PRICE)
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link filter__link--number" id="oriprice" href="#">
                                Tổng Tiền
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link filter__link--number" id="price" href="#">
                                Tổng doanh thu
                            </a>
                        </th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
        <div>
            <table cellpadding="0" cellspacing="0" border="0">
                <tbody class="table-content">
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr class="table-row">
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.BILL.ID)

                                </td>
                                <td class="table-data">
                                     @(item.DATE.ToString("dd/MM HH:mm"))

                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.BILL.ORI_PRICE)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.INCOME)
                                </td>
                                <td class="table-data">
                                    @item.Tongdoanhthu().ToString("N0");
                                </td>

                                <td style="display: flex;align-content: center;flex-wrap: wrap;flex-direction: column;">
                                    @*<a href="@Url.Action("Edit", "Product", new { id = item.ID })" class="btn btn-sm btn-warning" style="margin-bottom: 5px;">Edit</a>
                                        <a href="@Url.Action("Delete", "Product", new { id = item.ID })" class="btn btn-sm btn-danger" style="margin-bottom: 5px;">Delete</a>
                                        <a href="@Url.Action("Detail", "Product", new { id = item.ID })" class="btn btn-sm btn-info" style="margin-bottom: 5px;">Detail</a>*@
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

THDShop/THDShop/Areas/Manager/Views/Bill/Searchid.cshtml
@model IEnumerable<THDShop.BILL>

@{
    ViewBag.Title = "Index";
}
@using (Html.BeginForm("Searchid", "Bill"))
{
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Hóa Đơn</h1>
        <div class="input-group">
            <input type="text" name="id" class="form-control bg-light border-0 small" placeholder="Nhập mã hóa đơn"
                   aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="text-center">
        <div>
            <div class="tbl-header">
                <table cellpadding="0" cellspacing="0" border="0">
                    <thead class="table-header">
                        <tr>
                            <th class="header__item">
                                <a class="filter__link filter__link--number" id="id" href="#">
                                    Thời Gian
                                </a>
                            </th>
                            <th class="header__item">
                                <a class="filter__link filter__link--number" id="name" href="#">
                                    Mã HĐ
                                </a>
                            </th>
                            <th class="header__item">
                                <a class="filter__link" id="cate" href="#">
                                    Khách Hàng
                                </a>
                            </th>
                            <th class="header__item">
                                <a class="filter__link filter__link--number" id="oriprice" href="#">
                                    SĐT
                                </a>
                            </th>
                            <th class="header__item">
                                <a class="filter__link filter__link--number" id="price" href="#">
                                    Tổng Tiền
                                </a>
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div>
                <table cellpadding="0" cellspacing="0" border="0">
                    <tbody class="table-content">
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr class="table-row">
                                    <td class="table-data">
                                        @(item.DATETIME.ToString("dd/MM HH:mm"))
                                    </td>
                                    <td class="table-data">
                                        @Html.DisplayFor(modelItem => item.ID)
                                    </td>
                                    <td class="table-data">
                                        @Html.DisplayFor(modelItem => item.ORDER.DELI_ADDRESS.NAME)
                                    </td>
                                    <td class="table-data">
                                        @Html.DisplayFor(modelItem => item.ORDER.DELI_ADDRESS.PHONE)
                                    </td>
                                    <td class="table-data">
                                        @Html.DisplayFor(modelItem => item.TOTALMONEY)
                                    </td>
                                    <td style="display: flex;align-content: center;flex-wrap: wrap;flex-direction: column;">
                                        <a href="@Url.Action("Edit", "Product", new { id = item.ID })" class="btn btn-sm btn-warning" style="margin-bottom: 5px;">Edit</a>
                                        <a href="@Url.Action("Delete", "Product", new { id = item.ID })" class="btn btn-sm btn-danger" style="margin-bottom: 5px;">Delete</a>
                                        <a href="@Url.Action("Detail", "Product", new { id = item.ID })" class="btn btn-sm btn-info" style="margin-bottom: 5px;">Detail</a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}