THDShop/THDShop/Areas/Manager/Controllers/GiftController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using THDShop.ViewModel.Gift;
using System.Web.Mvc;

namespace THDShop.Areas.Manager.Controllers
{
    public class GiftController : Controller
    {

        QLLaptopShopEntities _db = new QLLaptopShopEntities();
        CUSTOMER cus;
        // GET: Manager/Gift
        public ActionResult Index()
        {
            if (Session["IDQL"] != null || Session["IDNV"] != null)
            {
                return View(_db.GIFTs.ToList());
            }
            return Redirect("/LoginCustomer/LoginAccount");
            
        }

        // GET: Manager/Gift/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Manager/Gift/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: QuanLy/KhuyenMai/Create
        [HttpPost]
        public ActionResult Create(CreateGiftInput model)
        {

            // TODO: Add insert logic here
            //_db.GIFTs.Add(gift);
            //_db.SaveChanges();
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = new GIFT();
                    if (model == null)
                    { entity = new GIFT(); }
                    entity.ID = model.ID;
                    entity.G_POINT = model.G_POINT;
                    entity.G_VALUE = model.G_VALUE;
                    entity.G_START = DateTime.Now;
                    entity.G_END = (DateTime)model.G_END;
                    entity.DESCREPTION = model.DESCREPTION;
                    entity.QUANTITY = model.QUANTITY;
                    _db.GIFTs.Add(entity);
                    _db.SaveChanges();

                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Create");
            }


        }

        // GET: Manager/Gift/Edit/5
        public ActionResult Edit(string id)
        {
            var entity = _db.GIFTs.Find(id);
            var model = new UpdateGiftInput();
            model.ID = entity.ID;
            model.G_POINT = entity.G_POINT;

            model.G_VALUE = entity.G_VALUE;
            model.G_START = (DateTime)entity.G_START;
            model.G_END = (DateTime)entity.G_END;
            model.DESCREPTION = entity.DESCREPTION;
            model.QUANTITY = entity.QUANTITY;
            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(UpdateGiftInput model)
        {
            var entity = new GIFT();
            if (model == null)
            { entity = new GIFT(); }
            entity.ID = model.ID;
            entity.G_POINT = model.G_POINT;
            entity.G_VALUE = model.G_VALUE;
            entity.G_START = (DateTime)model.G_START;
            entity.G_END = (DateTime)model.G_END;
            entity.DESCREPTION = model.DESCREPTION;
            entity.QUANTITY = model.QUANTITY;
            _db.GIFTs.Add(entity);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: QuanLy/KhachHang/Delete/5
        public ActionResult Delete(string id)
        {
            var entity = _db.GIFTs.Find(id);
            _db.GIFTs.Remove(entity);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
       
    }
}

THDShop/THDShop/Areas/Manager/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using THDShop;
using THDShop.ViewModel;
using THDShop.ViewModel.Product;


namespace THDShop.Areas.Manager.Controllers
{
    public class ProductController : Controller 
    {
        // GET: Manager/Product
        private QLLaptopShopEntities _context = new QLLaptopShopEntities();
        
      
        
        public ProductController( )
        {
            ProductSingleton.Instance.Init(_context);
        }

     
        public ActionResult Index(int id = 0)
        {
            //var query = from c in _context.PRODUCTS
            //            select new ProductDTO
            //            {
            //                ID = c.ID,
            //                NAME = c.NAME,
            //                PRICE = c.PRICE, 
            //                ORI_PRICE = c.ORI_PRICE,
            //                DESCRIPTION = c.DESCRIPTION,
            //                CATEGORYNAME = c.CATEGORy.NAME,
            //                IDCATEGORY = c.IDCATEGORY,
            //                QUANTITY = c.QUANTITY,
            //                IMAGE = c.IMAGE,
            //                DESCRIPTION_CPU = c.DESCRIPTION_CPU,
            //                DESCRIPTION_RAM = c.DESCRIPTION_RAM,
            //                DESCRIPTION_STORAGE = c.DESCRIPTION_STORAGE,
            //                DESCRIPTION_CARD = c.DESCRIPTION_CARD,
            //                DESCRIPTION_SCREEN = c.DESCRIPTION_SCREEN,
            //                DESCRIPTION_WEIGHT = c.DESCRIPTION_WEIGHT,
            //            };
            //return View(query.ToList());
            //var query = ProductSingleton.Instance.listProduct;
            //return View(query.ToList());
            if (Session["IDQL"] != null)
            {
                var links = from l in _context.PRODUCTS
                            select l;
                if (id != 0)
                {
                    links = links.Where(x => x.ID == id);
                    return View(links);
                }
                return View(links);
            }
            return Redirect("/LoginCustomer/LoginAccount");
        }
        
        public ActionResult Create()
        {
            var categorylist = _context.CATEGORIES.ToList().Select(
            x => new SelectListItem
            {
                Text = x.NAME,
                Value = Convert.ToString(x.ID)
            }
           );
            ViewBag.Categories = categorylist;
            CreateProductInput prod = new CreateProductInput();
            return View(prod);

        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(CreateProductInput model)
        {

            CalculateClient sales = new CalculateClient(new Sale_Price());
            var entity = new PRODUCT();
            if (model != null)
            {
                entity = new PRODUCT();
                var categorylist = _context.CATEGORIES.ToList().Select(
                x => new SelectListItem
                {
                    Text = x.NAME,
                    Value = Convert.ToString(x.ID)
                }
                );
                ViewBag.Categories = categorylist;
                if (model.UploadImage != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(model.UploadImage.FileName);
                    string extent = Path.GetExtension(model.UploadImage.FileName);
                    filename = filename + extent;
                    model.IMAGE = "~/Assets/Images/" + filename;
                    model.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Assets/Images"), filename));
                }
                entity.IMAGE = model.IMAGE;


                    if (ModelState.IsValid)
                {
                    var i = model.ORI_PRICE;
                    entity.ID = model.ID;
                    entity.NAME = model.NAME;
                    entity.ORI_PRICE = model.ORI_PRICE.HasValue ? model.ORI_PRICE.Value : 0;
                    entity.PRICE = sales.Calculate((int)i);
                    entity.QUANTITY = model.QUANTITY.HasValue ? model.QUANTITY.Value : 0;
                    entity.USD_PRICE = model.USD_PRICE(1);
                    entity.DESCRIPTION = model.DESCRIPTION;
                    entity.DESCRIPTION_CPU = model.DESCRIPTION_CPU;
                    entity.DESCRIPTION_RAM = model.DESCRIPTION_RAM;
                    entity.DESCRIPTION_STORAGE = model.DESCRIPTION_STORAGE;
                    entity.DESCRIPTION_CARD = model.DESCRIPTION_CARD;
                    entity.DESCRIPTION_SCREEN = model.DESCRIPTION_SCREEN;
                    entity.DESCRIPTION_WEIGHT = model.DESCRIPTION_WEIGHT;
                    entity.IDCATEGORY = model.IDCATEGORY;
                    _context.PRODUCTS.Add(entity);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {

                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }
        public ActionResult Edit(int ID)
        {
            var entity = _context.PRODUCTS.Find(ID);
            var model = new UpdateProductInput();
            var categorylist = _context.CATEGORIES.ToList().Select(
                x => new SelectListItem
                {
                    Text = x.NAME,
                    Value = Convert.ToString(x.ID)
                }
                );
            ViewBag.Categories = categorylist;
            model.ID = entity.ID;
            model.HOTPRODUCT = entity.HOTPRODUCT;
            model.NAME = entity.NAME;
            model.PRICE = entity.PRICE;
            model.ORI_PRICE = entity.ORI_PRICE;
            model.QUANTITY = entity.QUANTITY;
            model.DESCRIPTION = entity.DESCRIPTION;
            model.DESCRIPTION_CPU = entity.DESCRIPTION_CPU;
            model.DESCRIPTION_RAM = entity.DESCRIPTION_RAM;
            model.DESCRIPTION_STORAGE = entity.DESCRIPTION_STORAGE;
            model.DESCRIPTION_CARD = entity.DESCRIPTION_CARD;
            model.DESCRIPTION_SCREEN = entity.DESCRIPTION_SCREEN;
            model.DESCRIPTION_WEIGHT = entity.DESCRIPTION_WEIGHT;
            model.IDCATEGORY = entity.IDCATEGORY;
            model.IMAGE = entity.IMAGE;
            return View(model);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(UpdateProductInput model)
        {
            var entity = new PRODUCT();
            if (model == null)
                return HttpNotFound();

            var categorylist = _context.CATEGORIES.ToList().Select(
                x => new SelectListItem
                {
                    Text = x.NAME,
                    Value = Convert.ToString(x.ID)
                }
                );
            ViewBag.Categories = categorylist;

            if (model.UploadImage != null)
            {
                string filename = Path.GetFileNameWithoutExtension(model.UploadImage.FileName);
                string extent = Path.GetExtension(model.UploadImage.FileName);
                filename = filename + extent;
                model.IMAGE = "~/Assets/Images/" + filename;
                model.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Assets/Images"), filename));

            }
            entity.ID = model.ID;
            entity.HOTPRODUCT = model.HOTPRODUCT;
            entity.NAME = model.NAME;
            entity.PRICE = model.PRICE.HasValue ? model.PRICE.Value : 0;
            entity.ORI_PRICE = model.ORI_PRICE.HasValue ? model.ORI_PRICE.Value : 0;
            entity.USD_PRICE = model.USD_PRICE(1);
            entity.QUANTITY = model.QUANTITY.HasValue ? model.QUANTITY.Value : 0;
            entity.DESCRIPTION = model.DESCRIPTION;
            entity.DESCRIPTION_CPU = model.DESCRIPTION_CPU;
            entity.DESCRIPTION_RAM = model.DESCRIPTION_RAM;
            entity.DESCRIPTION_STORAGE = model.DESCRIPTION_STORAGE;
            entity.DESCRIPTION_CARD = model.DESCRIPTION_CARD;
            entity.DESCRIPTION_SCREEN = model.DESCRIPTION_SCREEN;
            entity.DESCRIPTION_WEIGHT = model.DESCRIPTION_WEIGHT;
            entity.IDCATEGORY = model.IDCATEGORY;
            entity.IMAGE = model.IMAGE;

            this._context.Entry(entity).State = EntityState.Modified;
            this._context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id, PRODUCT prod)
        {
            try
            {
                prod = _context.PRODUCTS.Where(s => s.ID == id).FirstOrDefault();
                _context.PRODUCTS.Remove(prod);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Dữ liệu này đang được sử dụng bởi một bảng khác");
            }
        }


        public ActionResult Detail(DetailProductDTO model, int ID)
        {
            var query = from c in _context.PRODUCTS
                        where c.ID == ID
                        select new DetailProductDTO
                        {
                            ID = c.ID,
                           // HOTPRODUCT = c.HOTPRODUCTS,
                            NAME = c.NAME,
                            PRICE = c.PRICE,
                            ORI_PRICE = c.ORI_PRICE,
                            QUANTITY = c.QUANTITY,
                            DESCRIPTION = c.DESCRIPTION,
                            IMAGE = c.IMAGE,

THDShop/THDShop/Areas/Manager/Views/Gift/Create.cshtml
@model THDShop.ViewModel.Gift.CreateGiftInput

@{
    ViewBag.Title = "Create";
}
<head>
    <link href="~/form/css/StyleSheet.css" rel="stylesheet" />
</head>
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Tạo voucher</h1>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div style="display: flex; align-items: flex-start;">
        <div class="text-center-box">
            <div class="paddingtop rl" style="padding-bottom: 20px;">
                <div class="form">
                    <!-- Mã -->
                    <div class="form-group">
                        @Html.EditorFor(model => model.ID, new { htmlAttributes = new { placeholder = "Mã Voucher" } })
                        @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                    </div>

                    <!-- Điểm để đổi -->
                    <div class="form-group ">
                        @Html.EditorFor(model => model.G_POINT, new { htmlAttributes = new { placeholder = "Điểm" } })
                        @Html.ValidationMessageFor(model => model.G_POINT, "", new { @class = "text-danger" })
                    </div>

                    <!-- Số Lượng -->
                    <div class="form-group">
                        @Html.EditorFor(model => model.G_VALUE, new { htmlAttributes = new { placeholder = "% Giảm (1-100)" } })
                        @Html.ValidationMessageFor(model => model.G_VALUE, "", new { @class = "text-danger" })
                    </div>

                    <!-- Thời gian bắt đầu -->
                    <div class="form-group">
                        @Html.EditorFor(model => model.G_START, new { htmlAttributes = new { placeholder = "Thời gian bắt đầu" } })
                        @Html.ValidationMessageFor(model => model.G_START, "", new { @class = "text-danger" })
                    </div>

                    <!-- Thời gian kết thúc -->
                    <div class="form-group">
                        @Html.EditorFor(model => model.G_END, new { htmlAttributes = new { placeholder = "Thời gian kết thúc" } })
                        @Html.ValidationMessageFor(model => model.G_END, "", new { @class = "text-danger" })
                    </div>

                    <!-- mô tả -->
                    <div class="form-group">
                        @Html.EditorFor(model => model.DESCREPTION, new { htmlAttributes = new { placeholder = "Mô tả voucher" } })
                        @Html.ValidationMessageFor(model => model.DESCREPTION, "", new { @class = "text-danger" })
                    </div>

                    <!-- số lượng -->
                    <div class="form-group">
                        @Html.EditorFor(model => model.QUANTITY, new { htmlAttributes = new { placeholder = "Số lượng" } })
                        @Html.ValidationMessageFor(model => model.QUANTITY, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Buttons -->
                <div>
                    <input class="btn btn-success" type="submit" value="Tạo" />
                    <span class="btn btn-link">@Html.ActionLink("Quay về", "Index") </span>
                </div>
            </div>
        </div>
    </div>
}

THDShop/THDShop/Areas/Manager/Views/Gift/Index.cshtml
@model IEnumerable<THDShop.GIFT>

@{
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Voucher</h1>
    <div class="input-group">
        <input type="text" name="name" class="form-control bg-light border-0 small" placeholder="Nhập mã voucher"
               aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit">
                <i class="fas fa-search fa-sm"></i>
            </button>
        </div>
    </div>
    <a href="@Url.Action("Create", "Gift")" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-download fa-sm text-white-50"></i> Tạo Voucher
    </a>
</div>
<div class="text-center">
    <div>
        <div class="tbl-header">
            <table cellpadding="0" cellspacing="0" border="0">
                <thead class="table-header">
                    <tr>
                        <th class="header__item">
                            <a class="filter__link filter__link--number" id="id" href="#">
                                Mã
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link filter__link--number" id="name" href="#">
                                Điểm thưởng
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link" id="cate" href="#">
                                Giá trị giảm
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link" id="cate" href="#">
                                Hiệu lực từ ngày
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link" id="cate" href="#">
                                Đến ngày
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link" id="cate" href="#">
                                Mô tả
                            </a>
                        </th>
                        <th class="header__item">
                            <a class="filter__link" id="cate" href="#">
                                Số lượng
                            </a>
                        </th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
        <div>
            <table cellpadding="0" cellspacing="0" border="0">
                <tbody class="table-content">
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr class="table-row">
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.ID)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.G_POINT)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.G_VALUE)
                                </td>
                                <td class="table-data">
                                    @item.G_START
                                    @*@item.G_START.ToString("dd/MM HH:mm")*@
                                </td>
                                <td class="table-data">
                                    @item.G_END
                                  @*  @item.G_END.ToString("dd/MM HH:mm")*@
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.DESCREPTION)
                                </td>
                                <td class="table-data">
                                    @Html.DisplayFor(modelItem => item.QUANTITY)
                                </td>
                                <td style="display: flex;align-content: center;flex-wrap: wrap;flex-direction: column;">
                                    <a href="@Url.Action("Edit", "Product", new { id = item.ID })" class="btn btn-sm btn-warning" style="margin-bottom: 5px;">Edit</a>
                                    <a href="@Url.Action("Delete", "Product", new { id = item.ID })" class="btn btn-sm btn-danger" style="margin-bottom: 5px;">Delete</a>
                                    <a href="@Url.Action("Detail", "Product", new { id = item.ID })" class="btn btn-sm btn-info" style="margin-bottom: 5px;">Detail</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@*<tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.G_POINT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.G_VALUE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.G_START)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.G_END)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DESCREPTION)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QUANTITY)
        </th>
        <th></th>
    </tr>*@





